name: stencil-circleci
arguments:
  reportingTeam: fnd-dt
  description: Stencil Module for CircleCI
  releaseOptions:
    enablePrereleases: true
    allowMajorVersions: true
    prereleasesBranch: rc
  ciOptions:
    skipDocker: true
    skipE2e: true
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
replacements:
  github.com/getoutreach/stencil-circleci: ./
