name: stencil-circleci
arguments:
  reportingTeam: fnd-dt
  description: Stencil Module for CircleCI
  releaseOptions:
    enablePrereleases: true
    allowMajorVersions: true
    prereleasesBranch: rc
  ciOptions:
    skipDocker: true
    skipE2e: true
  opslevel:
    confluenceSpaceKey: DT
    tier: 2
    lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
  - name: github.com/getoutreach/stencil-outreach
    channel: rc
replacements:
  github.com/getoutreach/stencil-circleci: ./
