name: stencil-circleci
arguments:
  reportingTeam: fnd-dt
  description: Stencil Module for CircleCI
  releaseOptions:
    enablePrereleases: true
    allowMajorVersions: true
    prereleasesBranch: rc
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-circleci
replacements:
  github.com/getoutreach/stencil-circleci: ./
