name: stencil-circleci
arguments:
  reportingTeam: fnd-dt
  description: Stencil Module for CircleCI
  releaseOptions:
    enablePrereleases: true
    allowMajorVersions: true
    autoPrereleases: true
    prereleasesCron: "0 19 * * 2"
    prereleasesBranch: main
  ciOptions:
    skipDocker: true
    skipE2e: true
  opslevel:
    confluenceSpaceKey: DT
    tier: 2
    lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/devbase
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-outreach
replacements:
  github.com/getoutreach/stencil-circleci: ./
